import type { GraphNode } from './types'

function loc(country: string, city: string) {
  return {
    countries: [country],
    cities: [`${country}|${city}`],
  }
}

/** Seed people so the pre-alpha graph feels inhabited. */
export const SEED_NODES: GraphNode[] = [
  {
    id: 'seed-1',
    name: 'ASTRID V.',
    role: 'member',
    ...loc('SWEDEN', 'STOCKHOLM'),
    skills: ['BUILD & CONSTRUCTION/CARPENTRY', 'CAMP OPERATIONS/KITCHEN & COOKING'],
    cocreated: ['2023', '2024', '2025'],
    visited: ['2023', '2024', '2025', '2026'],
  },
  {
    id: 'seed-2',
    name: 'JONAS K.',
    role: 'member',
    ...loc('SWEDEN', 'STOCKHOLM'),
    skills: ['LIGHT/LIGHTING DESIGN', 'TECH & INTERACTIVE/PROGRAMMING'],
    cocreated: ['2024', '2025', '2026'],
    visited: ['2024', '2025', '2026'],
  },
  {
    id: 'seed-3',
    name: 'MIRA L.',
    role: 'cocreator',
    ...loc('DENMARK', 'COPENHAGEN'),
    skills: ['PERFORMANCE/DANCE', 'SOUND/DJING'],
    cocreated: ['2025'],
    visited: ['2024', '2025', '2026'],
  },
  {
    id: 'seed-4',
    name: 'NOAH R.',
    role: 'cocreator',
    countries: ['GERMANY', 'NETHERLANDS'],
    cities: ['GERMANY|BERLIN', 'NETHERLANDS|AMSTERDAM'],
    skills: ['TECH & INTERACTIVE/ELECTRONICS / MICROCONTROLLERS', 'LIGHT/LASERS'],
    cocreated: ['2023', '2024'],
    visited: ['2023', '2024', '2025'],
  },
  {
    id: 'seed-5',
    name: 'ELIN S.',
    role: 'prospect',
    ...loc('SWEDEN', 'GOTHENBURG'),
    skills: ['ART & CRAFT/PAINTING / MURALS'],
    cocreated: [],
    visited: ['2026'],
  },
  {
    id: 'seed-6',
    name: 'CASPER T.',
    role: 'subscriber',
    ...loc('NETHERLANDS', 'AMSTERDAM'),
    skills: [],
    cocreated: [],
    visited: ['2025'],
  },
  {
    id: 'seed-7',
    name: 'YAEL M.',
    role: 'cocreator',
    ...loc('ISRAEL', 'TEL AVIV'),
    skills: ['SOUND/SOUND ENGINEERING / PA', 'PERFORMANCE/IMMERSIVE THEATRE & ACTING'],
    cocreated: ['2025', '2026'],
    visited: ['2025', '2026'],
  },
  {
    id: 'seed-8',
    name: 'OTTO B.',
    role: 'member',
    ...loc('GERMANY', 'BERLIN'),
    skills: ['BUILD & CONSTRUCTION/CARPENTRY', 'POWER & INFRASTRUCTURE/ELECTRICS & POWER GRID'],
    cocreated: ['2023', '2024', '2025', '2026'],
    visited: ['2023', '2024', '2025', '2026'],
  },
  {
    id: 'seed-9',
    name: 'FREJA H.',
    role: 'prospect',
    ...loc('NORWAY', 'OSLO'),
    skills: ['ART & CRAFT/TEXTILES & COSTUME'],
    cocreated: [],
    visited: ['2024', '2026'],
  },
  {
    id: 'seed-10',
    name: 'LEO P.',
    role: 'subscriber',
    ...loc('FRANCE', 'PARIS'),
    skills: [],
    cocreated: [],
    visited: [],
  },
  {
    id: 'seed-11',
    name: 'SAGA N.',
    role: 'cocreator',
    countries: ['SWEDEN', 'DENMARK'],
    cities: ['SWEDEN|MALMÖ', 'DENMARK|COPENHAGEN'],
    skills: ['LIGHT/PROJECTION MAPPING', 'TECH & INTERACTIVE/PROGRAMMING'],
    cocreated: ['2026'],
    visited: ['2025', '2026'],
  },
  {
    id: 'seed-12',
    name: 'IVAR D.',
    role: 'member',
    ...loc('DENMARK', 'COPENHAGEN'),
    skills: ['CAMP OPERATIONS/KITCHEN & COOKING', 'SOUND/DJING'],
    cocreated: ['2024', '2025'],
    visited: ['2023', '2024', '2025'],
  },
]
